name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - feature/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      SUPABASE_URL: http://127.0.0.1:54321
      SUPABASE_SERVICE_ROLE_KEY: test-service-role
      SUPABASE_ANON_KEY: test-anon
      ADMIN_SECRET: test-admin
      ADMIN_EMAILS: admin@example.com
      DOCKER_REGISTRY: docker.io
      DOCKER_ORG: ${{ secrets.DOCKER_ORG || secrets.DOCKER_USERNAME || github.repository_owner }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            client/package-lock.json

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm run test

      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Run frontend unit tests
        working-directory: client
        run: npm run test -- --run

      - name: Log in to Docker registry
        if: ${{ secrets.DOCKER_USERNAME }} && ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.DOCKER_REGISTRY }} -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build backend image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/volunteer-board-backend:${{ env.IMAGE_TAG }} ./server
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/volunteer-board-backend:${{ env.IMAGE_TAG }}
          fi

      - name: Build frontend image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/volunteer-board-frontend:${{ env.IMAGE_TAG }} ./client
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ]; then
            docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_ORG }}/volunteer-board-frontend:${{ env.IMAGE_TAG }}
          fi
