name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      SUPABASE_URL: http://127.0.0.1:54321
      SUPABASE_SERVICE_ROLE_KEY: test-service-role
      SUPABASE_ANON_KEY: test-anon
      ADMIN_SECRET: test-admin
      ADMIN_EMAILS: admin@example.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install backend dependencies
        working-directory: server
        run: npm install

      - name: Run backend tests
        working-directory: server
        run: npm run test

      - name: Install frontend dependencies
        working-directory: client
        run: npm install

      - name: Run frontend unit tests
        working-directory: client
        run: npm run test -- --run

      - name: Build backend image
        run: docker build -t volunteer-board-backend ./server

      - name: Build frontend image
        run: docker build -t volunteer-board-frontend ./client
