name: Preview Smoke Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL of the deployed frontend (e.g. https://preview-url.vercel.app)"
        required: true

jobs:
  smoke:
    name: Playwright smoke tests
    runs-on: ubuntu-latest
    env:
      E2E_BASE_URL: ${{ inputs.base_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: e2e/package-lock.json

      - name: Install Playwright dependencies
        working-directory: e2e
        run: npm install

      - name: Install Playwright browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Run smoke tests
        working-directory: e2e
        run: npm test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/artifacts/playwright-report
          if-no-files-found: ignore
